OBJECTS = 
CFLAGS = -g -Wall -O3 --std=c11
LDLIBS= -l criterion -lm
CC=clang

test_lab2: test_lab2.c lab2.c

my_echo: my_echo.c

clean:
	rm -f test_lab2 my_echo
	rm -rf *.dSYM *~ \#*
	rm -f test-*.txt testfile

