#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "round.h"
#include "util.h"

/* print_results: print the results of a round
 *
 * num_rounds: the number of the round
 * winner: the index of the winner or -1
 * info: the election information
 */
void print_round_results(int round_num, int winner, struct election_info info) {
  // Print the results
  printf("Round %d:\n", round_num);
  for (unsigned int i = 0; i < info.num_viable_candidates; i++) {
    printf("  %s: %d\n", info.candidates[i], info.counts[i]);
  }
  printf("\n  Exhausted_ballots: %d\n", info.exhausted_ballots);

  if (winner >= 0) {
    printf("Winner: %s\n", info.candidates[winner]);
  } else {
    printf("  Dropped candidate: %s: %d\n\n",
           info.candidates[info.num_viable_candidates - 1],
           info.counts[info.num_viable_candidates - 1]);
  }
}

/* run_election: run election rounds until a winner is declared.  Prints
 *   information about each round as it is run.
 *
 * ballot_filename: the name of the file containing the ballots
 * candidates_filename: the name of the file containing the candidates
 *
 * Returns: Nothing
 */
void run_election(char *ballot_filename, char *candidates_filename) {
  // Set up the information neeed for the election
  struct election_info info;

  info.ballots = read_ballots_from_file(ballot_filename, &info.num_ballots);
  if (info.ballots == NULL) {
    // Error message generated by read_ballots_from_file
    exit(1);
  }

  info.candidates =
      read_candidates_from_file(candidates_filename, &info.num_candidates);
  if (info.candidates == NULL) {
    // Error message generated by read_candidates_from_file
    exit(1);
  }
  // initially all the candidates are viable.
  info.num_viable_candidates = info.num_candidates;

  int counts[info.num_candidates];
  info.counts = counts;
  info.exhausted_ballots = 0;

  // Run the rounds
  int num_rounds = 0;
  while (info.exhausted_ballots < info.num_ballots) {
    // There is no need to run a round, if we are down to
    // one candidate.
    if (info.num_viable_candidates == 1) {
      printf("\nWinner (last one standing): %s\n", info.candidates[0]);
      break;
    }

    // initialize counts and exhausted ballots to sensible values
    // for each round
    for (unsigned int i = 0; i < info.num_viable_candidates; i++) {
      counts[i] = 0;
    }
    info.exhausted_ballots = 0;

    num_rounds++;
    int winner = run_round(&info);
    print_round_results(num_rounds, winner, info);

    if (winner < 0) {
      break;
    } else {
      // Drop the candidate in the last spot for the next round
      info.num_viable_candidates = info.num_viable_candidates - 1;
    }
  }

  // cleanup
  free_candidates(info.candidates, info.num_candidates);
  free_ballots(info.ballots, info.num_ballots);
}

/* parse_arguments: Construct the information needed to run a round.
 *
 * argc: the number of command-line arguments
 * argv: the command-line arguments
 *
 * Returns: true, if the arguments were successfully parsed and false,
 * otherwise.
 */
bool parse_arguments(int argc, char *argv[], char **ballots_filename,
                     char **candidates_filename) {
  int opt;
  char *usage = "Usage: %s -b ballot_filename -c candidate_filename [-h]\n";

  *ballots_filename = NULL;
  *candidates_filename = NULL;

  // Parse the arguments: expect both a ballot filename
  // and a candidate filename
  while ((opt = getopt(argc, argv, "b:c:h")) != -1) {
    switch (opt) {
      case 'b':
        if (*ballots_filename != NULL) {
          fprintf(stderr, "Error: Multiple ballot files supplied.\n");
          fprintf(stdout, usage, argv[0]);
          return false;
        }
        *ballots_filename = strdup(optarg);
        break;
      case 'c':
        if (*candidates_filename != NULL) {
          fprintf(stderr, "Error: Multiple candidates files supplied.\n");
          fprintf(stdout, usage, argv[0]);
          return false;
        }
        *candidates_filename = strdup(optarg);
        break;
      case 'h':
        fprintf(stdout, usage, argv[0]);
        return false;
      default:
        fprintf(stderr, usage, argv[0]);
        return false;
    }
  }

  if ((*ballots_filename == NULL) || (*candidates_filename == NULL)) {
    fprintf(stderr,
            "Error: missing one or both of the ballot and candidate file "
            "names.\n");
    fprintf(stderr, usage, argv[0]);
    return false;
  }

  return true;
}

int main(int argc, char *argv[]) {
  char *ballots_filename;
  char *candidates_filename;

  bool parse_successful =
      parse_arguments(argc, argv, &ballots_filename, &candidates_filename);
  if (parse_successful) {
    run_election(ballots_filename, candidates_filename);
  }

  if (ballots_filename != NULL) {
    free(ballots_filename);
  }
  if (candidates_filename != NULL) {
    free(candidates_filename);
  }

  if (parse_successful) {
    return 0;
  } else {
    // signal a failure.
    return 1;
  }
}
